[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "no-cache"
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Language = ["ar"]}
